#!/usr/bin/env python

import os

sourcedir='../sourcedir'
subjnum='200525'
destdir='..'

scanlist = [['mb_bold_mb6_2p5mm_Arterial_47', 'func', 'rest', 'arterialw_bold'],
            ['mb_bold_mb6_2p5mm_Arterial_SBRef_45', 'func', 'rest', 'arterialw_sbref'],
            ['mb_bold_mb6_2p5mm_Normal_43', 'func', 'rest', 'normal_bold'],
            ['mb_bold_mb6_2p5mm_Normal_SBRef_41', 'func', 'rest', 'normal_sbref'],
            ['SAG_T1_MPRAGE_ADNI3adv_32', 'anat', 'T1w'],
            ['mb_bold_mb6_2p5mm_SingleBH_55', 'func', 'bh', 'singlebh_bold'],
            ['mb_bold_mb6_2p5mm_SingleBH_SBRef_53', 'func', 'rest', 'singlebh_sbref'],
            ['mb_bold_mb6_2p5mm_Venous_51', 'func', 'rest', 'venousw_bold'],
            ['mb_bold_mb6_2p5mm_Venous_SBRef_49', 'func', 'rest', 'venous_sbref']]


for thescan in scanlist:
    cvtcmd = ['dcm2niix', '-b', 'y', '-ba', 'y', '-i', 'y', '-z', 'i', '-o']
    scanname = thescan[0]
    scantype = thescan[1]
    if scantype == 'func':
        outputpath = os.path.join(destdir, 'sub-' + subjnum, 'func')
        os.makedirs(outputpath, exist_ok=True)
        cvtcmd += [outputpath]
        scantask = thescan[2]
        scanacq = thescan[3]
        outputname = '_'.join(['sub-' + subjnum, 'task-' + scantask, 'acq-' + scanacq])
        
    else:
        outputpath = os.path.join(destdir, 'sub-' + subjnum, 'anat')
        os.makedirs(outputpath, exist_ok=True)
        cvtcmd += [outputpath]
        scanacq = thescan[2]
        outputname = '_'.join(['sub-' + subjnum, scanacq])
    cvtcmd += ['-f', outputname, os.path.join(sourcedir, 'sub-' + subjnum, scanname)]

    print(' '.join(cvtcmd))
