#!/usr/bin/env python

import os

sourcedir='home/despoB/emilyb/stroke_work_new/script_tester_stuff'
subjnum='00'
destdir='home/despoB/emilyb/test_script/test_output'

scanlist = [['T2_SPACE_SAG_P2_ISO_0008', 'func', 'rest', 'SPACE_SAG_TESTER']]


for thescan in scanlist:
    cvtcmd = ['dcm2niix', '-b', 'y', '-ba', 'y', '-i', 'y', '-z', 'i', '-o']
    scanname = thescan[0]
    scantype = thescan[1]
    if scantype == 'func':
        outputpath = os.path.join(destdir, 'sub-' + subjnum, 'func')
        os.makedirs(outputpath, exist_ok=True)
        cvtcmd += [outputpath]
        scantask = thescan[2]
        scanacq = thescan[3]
        outputname = '_'.join(['sub-' + subjnum, 'task-' + scantask, 'acq-' + scanacq])

    else:
        outputpath = os.path.join(destdir, 'sub-' + subjnum, 'anat')
        os.makedirs(outputpath, exist_ok=True)
        cvtcmd += [outputpath]
        scanacq = thescan[2]
        outputname = '_'.join(['sub-' + subjnum, scanacq])
    cvtcmd += ['-f', outputname, os.path.join(sourcedir, 'sub-' + subjnum, scanname)]

    print(' '.join(cvtcmd))


###
#OUTPUT:
#dcm2niix -b y -ba y -i y -z i -o home/despoB/emilyb/test_script
#/test_output/sub-00/func -f sub-00_task-rest_acq-SPACE_SAG_TESTER home/despoB
#/emilyb/stroke_work_new/script_tester_stuff/sub-00/T2_SPACE_SAG_P2_ISO_0008
